### ISSUE TITLE
upgrade to higher version of laravel 

### ISSUE THREAD

**Issue by solos10x** [barbosa89/welkome#13]
good day 
i was wandering if there is any way possible you can update the laravel version to maybe 5.8 above 
thanks

**Comment by barbosa89** [comment]
Hi, the project is running with Laravel 7 and PHP 7.4, have you the last changes from master branch?

In the next days will be released the first stable version with PayPal support, custom configurations, Laravel 8 support, PHP 7.4 and PHP 8.

**Comment by solos10x** [comment]
Oh I thing my php version is lower I will upgrade and run it again....
This will be nice PayPal is kind of popular I can't wait to see the update
on that.

Kind regard
